### ISSUE TITLE
Cannot download ticket. CDHash must be set.

### ISSUE THREAD

**Issue by Sherlozk** [electron/notarize#130]
yarn run v1.22.19
$ electron-forge make
✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets: zip
❯ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets: zip
❯ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
      ✔ [plugin-webpack] Preparing native dependencies
      ✔ [plugin-webpack] Building webpack bundles
  ❯ Packaging application
    ❯ Packaging for x64 on darwin
      ✔ Copying files
      ✔ Preparing native dependencies [0.1s]
      ✖ Finalizing package
        › Failed to staple your application with code: 66
          Processing: /private/var/folders/j7/my0z55j13vb5pm_5_hg66tlw0000gn/T/electron-packager/darwin-x64/xxx-darwin-x64-JLUQHk/xxxx.app
          Properties are {
          NSURLIsDirectoryKey = 1;
          NSURLIsPackageKey = 1;
          NSURLIsSymbolicLinkKey = 0;
          NSURLLocalizedTypeDescriptionKey = Application;
          NSURLTypeIdentifierKey = "com.apple.application-bundle";
          "_NSURLIsApplicationKey" = 1;
          }
          Props are {
          }
          Cannot download ticket. CDHash must be set.
  ◼ Running postPackage hook
◼ Running preMake hook
◼ Making distributables
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Failed to staple your application with code: 66

Processing: /private/var/folders/j7/my0z55j13vb5pm_5_hg66tlw0000gn/T/electron-packager/darwin-x64/xxxx-darwin-x64-JLUQHk/xxxx.app
Properties are {
    NSURLIsDirectoryKey = 1;
    NSURLIsPackageKey = 1;
    NSURLIsSymbolicLinkKey = 0;
    NSURLLocalizedTypeDescriptionKey = Application;
    NSURLTypeIdentifierKey = "com.apple.application-bundle";
    "_NSURLIsApplicationKey" = 1;
}
Props are {
}
Cannot download ticket. CDHash must be set.
at Object.<anonymous> (/Users/sherlock/Git/xxxx/node_modules/@electron/notarize/lib/staple.js:22:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sherlock/Git/xxxx/node_modules/@electron/notarize/lib/staple.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Sherlozk** [comment]
I know what happened，because app was unsigned

[How to sign electron app using electron forge?](https://stackoverflow.com/questions/46480682/how-to-sign-electron-app-using-electron-forge)
