### ISSUE TITLE
Notarize fails on multi platform (x64, aarch64) build.

### ISSUE THREAD

**Issue by sprout2000** [electron/notarize#136]
Notarization fails when both x64 and arm64 targets are set, requesting the value of the environment variable named **APPLE_APP_SPECIFIC_PASSWORD**.

```sh
/Foo/sample/node_modules/app-builder-lib/src/macPackager.ts:505
      throw new InvalidConfigurationError(`APPLE_APP_SPECIFIC_PASSWORD env var needs to be set`)
            ^
InvalidConfigurationError: APPLE_APP_SPECIFIC_PASSWORD env var needs to be set
    at MacPackager.notarizeIfProvided (/Foo/sample/node_modules/app-builder-lib/src/macPackager.ts:505:13)
    at MacPackager.sign (/Foo/sample/node_modules/app-builder-lib/src/macPackager.ts:339:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Foo/sample/node_modules/app-builder-lib/src/macPackager.ts:470:11
```

**Where do I set this APPLE_APP_SPECIFIC_PASSWORD environment variable?** Does anyone have any information on this?

Here is my build and notarization scripts:

- electron-builder: `builder.ts`

```ts
import { build } from "electron-builder";

build({
  config: {
    productName: "Sample",
    appId: "com.example.Sample",
    artifactName: "${productName}-${version}-${platform}-${arch}.${ext}",
    directories: {
      output: "release",
      buildResources: "assets",
    },
    mac: {
      target: [
        {
          target: "default",
          arch: ["x64", "arm64"],
        },
      ],
      icon: "assets/icon.icns",
    },
    afterSign: "scripts/notarizer.ts",
  },
});
```

- afterSign hook: `notarizer.ts`

```ts
import { notarize } from "@electron/notarize";
import type { AfterPackContext } from "electron-builder";

import dotenv from "dotenv";
dotenv.config();

const notarizer = async (context: AfterPackContext) => {
  const { appOutDir } = context;
  const appName = context.packager.appInfo.productFilename;

  return notarize({
    tool: "notarytool",
    appPath: `${appOutDir}/${appName}.app`,
    appleId: `${process.env.APPLE_ID}`,
    appleIdPassword: `${process.env.APPLE_ID_PASSWORD}`,
    teamId: `${process.env.ASC_PROVIDER}`,
  });
};

export default notarizer;
```

**Comment by sprout2000** [comment]
Solved.

Setting APPLE_APP_SPECIFIC_PASSWORD to .env and passing it as an option to the notarization function was successful.

- `.env` (All values are dummy)

```sh
APPLE_APP_SPECIFIC_PASSWORD="jetk-hsgm-kykz-sitm"
```

- `notarizer.ts`

```ts
import dotenv from "dotenv";
dotenv.config();

  return notarize({
    tool: "notarytool",
    appleIdPassword: `${process.env.APPLE_APP_SPECIFIC_PASSWORD}`,
  });
```

**Comment by raphaelmenges** [comment]
Hello @sprout2000! I am facing the same issue. Does anybody know, why this environment variable is expected / its name is hardcoded? I would expect the following in the `notarize` call to be sufficient:

```
appleIdPassword: `${process.env.APPLE_ID_PASSWORD}`,
```
